CREATE TABLE user(
	id INT IDENTITY PRIMARY KEY NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name  VARCHAR(50) NOT NULL,
    email  VARCHAR(50) NOT NULL,
	username  VARCHAR(30) NOT NULL,
	password  VARCHAR(32) NOT NULL
);