server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  datacenter: porto-alegre
  environment: development
  instance:
    lease-expiration-duration-in-seconds: 40
  server:
    eviction-interval-timer-in-ms: 4500
    expected-client-renewal-interval-seconds: 25
    renewal-threshold-update-interval-ms: 35000
logging:
  level:
    com:
      netflix:
      eureka: OFF
      discovery: OFF