spring:
  application:
    name: user-management-microservice
  datasource:
    driverClassName: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:/db/liquibase-changelog.yaml

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.uuid}