server:
  port: 8888
spring:
  application:
    name: photoapp-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeonardoBerlatto/microservices-cloud-config
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          search-paths:
            - 'user-management-microservice*'
            - 'zuul-api-gateway*'
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}